# Generated by Django 5.1.1 on 2024-11-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('nombre_equipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=254)),
                ('fecha_limite', models.DateField(help_text='Formato dd-mm-YYYY')),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=1)),
                ('estado', models.IntegerField(choices=[(1, 'Terminado'), (2, 'En proceso'), (3, 'Pendiente'), (4, 'Cancelada')])),
                ('observaciones', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('L', 'Lider'), ('D', 'Desarrollador')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones_Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obsevaciones_cambiada', models.CharField(max_length=254)),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tareas')),
                ('usuario_observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tareas')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos_Desarrollo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.equipos')),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tareas')),
                ('desarrollador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='usuario_lider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.usuarios'),
        ),
    ]
