# Generated by Django 5.1.1 on 2024-11-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones_tareas',
            name='obsevaciones_cambiada',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
