# Generated by Django 5.1.1 on 2024-11-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_equipos_desarrollo_tarea_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
